Auto <- read.csv("Auto.csv", na.strings = "?",
                 stringsAsFactors = T)
Auto <- na.omit(Auto)
str(Auto)
## I think "name" and "origin" are qualitiative, the other variables are quantitative
range(Auto$mpg)
range(Auto$cylinders)
range(Auto$displacement)
range(Auto$horsepower)
range(Auto$weight)
range(Auto$acceleration)
range(Auto$year)
summary(Auto[,1:7])
sd(Auto$mpg)
sd(Auto$cylinders)
sd(Auto$displacement)
sd(Auto$horsepower)
sd(Auto$weight)
sd(Auto$acceleration)
sd(Auto$year)
subset<- Auto[-c(10:85),(1:8)]
range(subset$mpg)
range(subset$cylinders)
range(subset$displacement)
range(subset$horsepower)
range(subset$weight)
range(subset$acceleration)
range(subset$year)
range(subset$origin)
summary(subset)
sd(subset$mpg)
sd(subset$cylinders)
sd(subset$displacement)
sd(subset$horsepower)
sd(subset$weight)
sd(subset$acceleration)
sd(subset$year)
sd(subset$origin)
pairs(Auto)
##9(e) As the scatterplots shown, there are some obvious linear and non-linear relationships among the predictors. For example, mpg and horsepower have a non-linear relationship, mpg decrease as horsepower increase;Displacement and weight have a near linear relationship, displacement increase as weight increase.
##9(f) As the scatterplots shown, cylinders, horsepower, year, origin might be useful in predicting mpg becasue they have obvious linear and non-linear relationships. Cylinders=4 tend to have higher mpg, Japanese cars (origin=3) tend to have higher mpg than US and Eurepeans, mpg increase as the year increase but mpg decrease as the horsepower increase. 